### ISSUE TITLE
Canvas images are not captured

### ISSUE THREAD

**Issue by satheeq** [gitawego/cordova-screenshot#113]
Screen shot does not contain any canvas images.

**Comment by matiasmicheletto** [comment]
Happened the same to me. Using the android emulator (Nexus 5 API 22) the canvas is visible, but not in my smartphone (android 6.0.1).

**Comment by jjosef** [comment]
Same problem

**Comment by matiasmicheletto** [comment]
A way to overcome this is using a <img> element instead of a <canvas>, and put a canvas capture as the src attribute of the image.

**Comment by satheeq** [comment]
@matiasmicheletto is that supported by the plugin?

**Comment by matiasmicheletto** [comment]
@satheeq The plugin works well with different html elements but somehow it fails when capturing canvas drawings. Because there is no problem on capturing img images you can use one of these instead of a canvas.
Depending on whether the canvas has dinamic or static content, the img element can be visible and the canvas an auxiliary hide element or the img be an auxiliary element that turns visible only at the time of taking the capture.
For example:

html file:
    ...
    <img id="auximg"/>
    ...

    
js file:
...
var cvs = document.createElement('canvas'); // Create a canvas or use existing
...
// Draw on the canvas
...
var auximg = document.getElementById('auximg'); // Get the img element
// Set the image dimensions (not sure if required)
auximg.width = cvs.width;
auximg.height = cvs.height;
auximg.src = cvs.toDataURL(); // Pass the canvas content to the img element
...

If the img is an auxiliary element that turns visible only during the screen capture, it is necessary to give a few milliseconds before perfoming the screenshot. Use setTimeout.
Hope this help.

**Comment by satheeq** [comment]
That worked well.
Thanks alot @matiasmicheletto
